[project]
name = "demucspleeter"
version = "0.0.13"
description = "AI-powered vocal separation using Demucs and Spleeter with YouTube downloader"
readme = "README.md"
requires-python = ">=3.10.0, <3.11.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "demucs",
    "spleeter",
    "torch",
    "torchaudio",
    "torchcodec==0.11.1",
    "requests",
    "colorama",
    "tqdm",
    "soundfile",
    "yt-dlp",
    "python-multipart",
    "psutil",
    "watchfiles",
    "numpy<2.0.0",
    "scipy<1.14.0",
]

[project.scripts]
demucspleeter = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["backend", "main.py"]

[tool.uv]
required-environments = ["sys_platform == 'win32'"]
override-dependencies = [
    "tensorflow-io-gcs-filesystem==0.31.0; sys_platform == 'win32'",
]

[tool.uv.workspace]
members = [
    "spleeter_env",
]
